# -*- coding: utf-8 -*-
"""jogoVelha3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NnSKpUKnQWxdNRBHc3CrHtHXYtdnRoPA
"""

print('JetBrains Academy Tic-Tac-Toe by Diego Cravo')
print('The coordinates:')
print('---------')
print(f'| (1 3) (2 3) (3 3) |')
print(f'| (1 2) (2 2) (2 3) |')
print(f'| (1 1) (1 2) (1 3) |')
print('---------')
print('X Starts!')

vitoria = [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']
contador = 0
def tabuleiro():
    print('---------')
    print(f'| {vitoria[0]} {vitoria[1]} {vitoria[2]} |')
    print(f'| {vitoria[3]} {vitoria[4]} {vitoria[5]} |')
    print(f'| {vitoria[6]} {vitoria[7]} {vitoria[8]} |')
    print('---------')

def check(x):
    global vitoria, checar
    if check_empty():
        if entrada1 == 1 and entrada2 == 1:
            vitoria[6] = x 
            return True  
        elif entrada1 == 1 and entrada2 == 2:
            vitoria[3] = x 
            return True 
        elif entrada1 == 1 and entrada2 == 3:
            vitoria[0] = x 
            return True
        elif entrada1 == 2 and entrada2 == 1:
            vitoria[7] = x 
            return True
        elif entrada1 == 2 and entrada2 == 2:
            vitoria[4] = x 
            return True
        elif entrada1 == 2 and entrada2 == 3:
            vitoria[1] = x   
            return True    
        elif entrada1 == 3 and entrada2 == 1:
            vitoria[8] = x 
            return True  
        elif entrada1 == 3 and entrada2 == 2:
            vitoria[5] = x 
            return True  
        elif entrada1 == 3 and entrada2 == 3:
            vitoria[2] = x 
            return True
        return False
 
def check_empty():
    global vitoria, checar
    if entrada1 == 1 and entrada2 == 1:
        if vitoria[6] == ' ' or vitoria[6] == '_':
            return True  
        elif vitoria[6] == 'X' or vitoria[6] == 'O':
            return False
    elif entrada1 == 1 and entrada2 == 2:
        if vitoria[3] == ' ' or vitoria[3] == '_': 
            return True 
        elif vitoria[3] == 'X' or vitoria[3] == 'O':
            return False
    elif entrada1 == 1 and entrada2 == 3:
        if vitoria[0] == ' ' or vitoria[0] == '_': 
            return True
        elif vitoria[0] == 'X' or vitoria[0] == 'O':
            return False
    elif entrada1 == 2 and entrada2 == 1:
        if vitoria[7] == ' ' or vitoria[7] == '_': 
            return True
        elif vitoria[7] == 'X' or vitoria[7] == 'O':
            return False
    elif entrada1 == 2 and entrada2 == 2:
        if vitoria[4] == ' ' or vitoria[4] == '_': 
            return True
        elif vitoria[4] == 'X' or vitoria[4] == 'O':
            return False
    elif entrada1 == 2 and entrada2 == 3:
        if vitoria[1] == ' ' or vitoria[1] == '_': 
            return True    
        elif vitoria[1] == 'X' or vitoria[1] == 'O':
            return False
    elif entrada1 == 3 and entrada2 == 1:
        if vitoria[8] == ' ' or vitoria[8] == '_': 
            return True  
        elif vitoria[8] == 'X' or vitoria[8] == 'O':
            return False
    elif entrada1 == 3 and entrada2 == 2:
        if vitoria[5] == ' ' or vitoria[5] == '_': 
            return True  
        elif vitoria[5] == 'X' or vitoria[5] == 'O':
            return False
    elif entrada1 == 3 and entrada2 == 3:
        if vitoria[2] == ' ' or vitoria[2] == '_': 
            return True
        elif vitoria[2] == 'X' or vitoria[2] == 'O':
            return False

def entrada_valida():
    loop = True
    while loop == True:
        global entrada1, entrada2, ent1, ent2, contador
        entrada = input('Enter the coordinates:')
        entradas = entrada.split()
        if len(entradas) != 2:
            print('You should enter numbers!')
            continue
        else: 
            ent1 = entradas[0]
            ent2 = entradas[1]
        if ent1.isnumeric() == False or ent2.isnumeric() == False:
            print('You should enter numbers!')
            continue
        entrada1 = int(ent1)
        entrada2 = int(ent2)
        if entrada1 < 1 or entrada1 > 3 or entrada2 < 1 or entrada2 > 3:
            print('Coordinates should be from 1 to 3!')
            continue
        if check_empty() == False:
            print('This cell is occupied! Choose another one!')
            continue
        else:
            loop = False

def xoro():
    global contador
    if contador % 2 == 0:
        check('X')
        contador += 1
    elif contador % 2 != 0:
        check('O')
        contador += 1

def xwin():
    if vitoria[0] == vitoria[1] == vitoria[2]  == 'X' or vitoria[3] == vitoria[4] == vitoria[5]  == 'X' or vitoria[6] == vitoria[7] == vitoria[8]  == 'X' or vitoria[0] == vitoria[3] == vitoria[6]  == 'X' or vitoria[1] == vitoria[4] == vitoria[7]  == 'X' or vitoria[2] == vitoria[5] == vitoria[8]  == 'X' or vitoria[0] == vitoria[4] == vitoria[8]  == 'X' or vitoria[6] == vitoria[4] == vitoria[2] == 'X':
        return True
    else:
        return False

def owin():
    if vitoria[0] == vitoria[1] == vitoria[2]  == 'O' or vitoria[3] == vitoria[4] == vitoria[5]  == 'O' or vitoria[6] == vitoria[7] == vitoria[8]  == 'O' or vitoria[0] == vitoria[3] == vitoria[6]  == 'O' or vitoria[1] == vitoria[4] == vitoria[7]  == 'O' or vitoria[2] == vitoria[5] == vitoria[8]  == 'O' or vitoria[0] == vitoria[4] == vitoria[8]  == 'O' or vitoria[6] == vitoria[4] == vitoria[2] == 'O':
        return True
    else:
        return False

def draw():
    if contador == 8 and xwin() == False and owin() == False:
        return False

end = False
tabuleiro()
while end == False:
    global vitoria
    entrada_valida()
    xoro()
    tabuleiro()
    if draw():
        print('Draw')
        end = True
        break
    elif owin():
        print('O wins')
        end = True
        break
    elif xwin():
        print('X wins')
        end = True
        break